### ISSUE TITLE
Windows 7 issue

### ISSUE THREAD

**Issue by n1msk** [QNetITQ/WaveFox#11]
![](https://user-images.githubusercontent.com/88570704/132787317-d7f61c63-9533-4d86-8cde-cfb1dbb83c17.png)

There appears to be a weird overlay that makes the aero theme and window buttons look washed out and not as saturated. Compared to your screenshot, I think you can see it looks quite different.

I don't think this is specific to your theme as it was there when I first installed Firefox. But maybe you know how to fix it?

**Comment by n1msk** [comment]
![](https://user-images.githubusercontent.com/88570704/132787715-b0c44bde-354e-42b4-8941-18919e25d54d.png)

It's like a gradient almost. It's a lot more noticable when I turned on the title bar.

**Comment by n1msk** [comment]
I fixed it with
`#TabsToolbar {
	background-image: none !important;
}`

Sorry to waste your time!

**Comment by QNetITQ** [comment]
Hi. This gradient is only available on the system theme. I left it on purpose so that black fonts would be visible even on a black background. Light and dark themes do not have gradients, but the user will have to independently choose the background through the capabilities of the system. I will update screenshots for better clarity.

**Comment by n1msk** [comment]
I think the background would be fine as long as it doesn't cover up the minimize/maximize/close buttons.
