### ISSUE TITLE
Tabs cannot be hidden after use this

### ISSUE THREAD

**Issue by yujinlin0224** [QNetITQ/WaveFox#119]
I am using https://github.com/Drive4ik/simple-tab-groups to manage my tabs, this plugin will make some tabs hidden to work, but it doesn't after use WaveFox.
Then I track the source code and found this make tabs cannot be hidden, but why?

https://github.com/QNetITQ/WaveFox/blob/9e70b7a7233295492162f5863e412ba5c8ebf80d/chrome/userChrome.css#L303-L318

**Comment by QNetITQ** [comment]
Mozilla removed the code that allowed working with hidden tabs. I can replace this code with the web standard, but its support has not yet been added to the browser. Therefore, I have to work with hidden tabs as normal, otherwise there may be problems with separators and tab indents. I'll fix it as soon as possible.

Support [added](https://bugzilla.mozilla.org/show_bug.cgi?id=1774588) in Firefox 112. You have to wait a month.

**Comment by yujinlin0224** [comment]
OK, I am not using separators and tab indents, I will temporary comment those lines and wait to next month

**Comment by QNetITQ** [comment]
Mozilla moved all major changes to v113. So we'll have to wait until May.

**Comment by QNetITQ** [comment]
Fixed issues with hidden tabs. There are still minor bugs, but they will be fixed a little later. The fixes are not yet stable, since Mozilla has not yet fully added support for the desired functionality. You can try with Nightly 113.

**Comment by yujinlin0224** [comment]
I am using Firefox Dev version now, I can wait

**Comment by QNetITQ** [comment]
The fix is ready. Mozilla has not yet fully implemented the features I need, but this will change in the near future, I hope.
