### ISSUE TITLE
Making custom tab styles

### ISSUE THREAD

**Issue by superdragon1772** [QNetITQ/WaveFox#148]
I tried editing the svgs (chrome\special\tabs\option_7) in adobe illustrator, but it didn't seem to work. Any advice?

**Comment by QNetITQ** [comment]
Do not change the svg file itself to another one. Change only the contents of the quotes of the **d** attribute. And remember that the svg is drawn on an infinite canvas by default. You must first specify the correct coordinate system. It must match the viewBox attribute.

**Comment by superdragon1772** [comment]
Apologies, but I do not know what you are explaining. I have not used illustrator before, I only looked up where to edit svgs. Could you explain exactly how and where I make my edits?

**Comment by QNetITQ** [comment]
It won't be short here. I use inkscape, not adobe illustrator. [Download it](https://inkscape.org/), it's free. [Here](http://tavmjong.free.fr/INKSCAPE/MANUAL/html/index.php) is a short guide to using it. I don't know if you understand something, since SVG is XML. Without knowing XML, it will be difficult for you to understand certain points. But it will do for a start.

**Comment by superdragon1772** [comment]
Okay. Thanks for the help though!
