### ISSUE TITLE
Everything works great, except transparency

### ISSUE THREAD

**Issue by ToneyFoxxy** [QNetITQ/WaveFox#179]
I've restarted LibreWolf several times, the rest of the userChrome seems to function correctly. On KDE Plasma with Kvantum using a definitely very transparent theme (Gently + Kvantum Gently). Worth noting that the higher I set the transparency setting, the more broken it seems to get
<img src="https://i.imgur.com/wbN3XDL.png"></img>

**Comment by ToneyFoxxy** [comment]
Nevermind, answer is in closed issues. Perhaps you should add a note to the readme?

**Comment by QNetITQ** [comment]
What issue are you referring to?

**Comment by ToneyFoxxy** [comment]
If you mean about transparency; https://github.com/QNetITQ/WaveFox/issues/149

**Comment by QNetITQ** [comment]
Issue #149 has nothing to do with Linux. It looks like you mean issue #102. I'll add a link to this issue in the description.

**Comment by QNetITQ** [comment]
Added a link.

**Comment by ToneyFoxxy** [comment]
No, I wasn't referring to that. There isn't any transparency happening. Look at the screenshot...

**Comment by QNetITQ** [comment]
Then I don't know. Transparency works for me. Maybe it's your Linux distribution, maybe it's the OS theme, or maybe the style version doesn't match the browser version. In any case, if everything is working for you now, then you don’t have to think about it.

**Comment by ToneyFoxxy** [comment]
Nah, I actually decided to not use this For both of the reasons I stated before, which both remain unresolved

**Comment by QNetITQ** [comment]
I don’t understand, are you trying to demand something from me now? I don't owe anything to anyone.

> Nevermind, answer is in closed issues.

After that, I concluded that you solved your problem yourself, but it turns out not. Next time, if there is one at all, express your thoughts more precisely.

**Comment by ToneyFoxxy** [comment]
I literally sent you a screenshot of the problem

**Comment by QNetITQ** [comment]
Well, yes. And then you literally wrote

> Nevermind, answer is in closed issues. Perhaps you should add a note to the readme?

I thought that you solved your problem yourself and wanted to know how. You sent me a link to a bug report that has nothing to do with Linux. And then it turns out that you haven’t solved your problem. Why then write that you solved it? You just misled me.

But this doesn’t matter anymore, because then you started insulting me. It's not enough for you that I spend my time solving your problem. You're just an uncultured boor who disrespects other people. I will not tolerate such an attitude. Until you change your attitude, don’t write here.

P.S.
Sorry if I offended you in any way. I did not want. But here you are completely wrong.

**Comment by ToneyFoxxy** [comment]
"Starting with Firefox 117, transparency is not supported by the browser."

Also, you never did jack shit to try to solve my problem, you only blamed my problem on me. Those are not the same thing

**Comment by QNetITQ** [comment]
> Starting with Firefox 117, transparency is not supported by the browser.

This only applies to Windows (Mica / Acrylic). Each system has its own methods for using transparency. On Linux, transparency is supported and works if the conditions in the description are met.

> Also, you never did jack shit to try to solve my problem, you only blamed my problem on me. Those are not the same thing

Didn't try to solve your problem? However, my actions say otherwise.
- Have I responded to your problem? Yes.
- Was I trying to figure it out? Had tried. And I figured it out.
- I rechecked the transparency on Linux and everything works for me. So I can't confirm your problem. Other users don’t write bug reports to me about this, as you can see.

Are you tired of complaining to me yet? Well, I don’t owe anything to anyone! How much more do I need to explain this? Read the license terms. Only politeness and mutual respect can help. There is no other way! You are not my boss, and I am not your subordinate. There are only horizontal connections, not vertical ones.
