### ISSUE TITLE
Navbar not transparent in new window

### ISSUE THREAD

**Issue by T0biasCZe** [QNetITQ/WaveFox#198]
When web opens new window, the navigation bar isnt transparent like in normal window
![image](https://github.com/QNetITQ/WaveFox/assets/44525446/2741b468-ec91-493d-942a-c897615be075)
example:
```
    <a href="https://example.com"  
    onclick="window.open('https://example.com', 
    'newwindow', 
    'width=300,height=250'); 
    return false;"
    >Test</a>
```

**Comment by QNetITQ** [comment]
The style is not applied to some windows. Although I haven’t encountered this for a long time. I'll try to reproduce and fix it if I can.

**Comment by Not-A-Coder2023** [comment]
I think WaveFox for Firefox 115 is broken on the Midori browser. I use the Windows version and everything works, except for the sudden absence of the first two "Close Multiple Tabs" options. Installing the newest version doesn't exactly help matters much.

**Comment by QNetITQ** [comment]
@T0biasCZe 
I checked everything. The style file is applied to this window. However, styles bound to the `[tabsintitlebar]` attribute are not applied. This attribute is used to determine whether tabs are in the title bar or whether the system's title bar is active. In order for transparency to apply to this window, I will have to abandon this attribute. This is not critical, but not advisable. I'll think about it some more.

@Not-A-Coder2023 
I tested the style on Midori. There is a bug with the tab close menu. This is strange since my style doesn't modify these menus. I checked on the original Firefox 115 ESR and there is no bug there. So this is a bug on Midori's part.
![Снимок](https://github.com/QNetITQ/WaveFox/assets/85301851/2d5eabbe-6630-4f7e-84e9-321f31d7fdf9)

**Comment by QNetITQ** [comment]
I changed the transparency of the toolbar. Everything should work in the next release.

**Comment by T0biasCZe** [comment]
Will that one work on 115 though?
Since never versions removed transparency support on Windows :|

**Comment by T0biasCZe** [comment]
Firefox Nightly 134.0a1, Wavefox 1.7.133, and the navbar is still opaque...

![image](https://github.com/user-attachments/assets/6eaa17dc-eb70-4cf0-8e8f-bbcdac62b56a)

**Comment by QNetITQ** [comment]
The option works as intended. To have transparency on these windows, you need to use additional rules. I can't add them to the style, because I don't interfere with the system design anymore. But you can add these rules yourself. Just add them to the style file.

```
:root,
#navigator-toolbox
{
    background-color: transparent !important;
}
```
