### ISSUE TITLE
Could this be a bug? Maybe separators?

### ISSUE THREAD

**Issue by Minibus93** [QNetITQ/WaveFox#217]
![Screenshot 2024-11-07 191017](https://github.com/user-attachments/assets/fe9d7acb-5832-4c8e-bbcb-f1094197549a)

When opening a certain amount of tabs (12 in my case) on the right most one this black bar appears. Could this be due WaveFox? 

```
WaveFox v1.7.132
Firefox 132.0.1
Windows 11 23H2

// WaveFox entries
user_pref("userChrome.Tabs.Option7.Enabled", true);
user_pref("userChrome.DarkTheme.Tabs.Borders.Enabled", true);
user_pref("userChrome.DarkTheme.Tabs.Shadows.Saturation.VeryHigh.Enabled", true);
user_pref("userChrome.TabSeparators.Saturation.Medium.Enabled", true);
```

On a side note, thanks for all the effort you put in making WaveFox so great! <3

**Comment by QNetITQ** [comment]
This is due to a rounding error in fractional numbers. I've looked into this issue and have concluded that it's due to the tab counter. It takes up a non-whole number of the tab bar width. This causes tabs to fail to calculate their padding correctly in some cases. I fixed this in v1.7.133. It seems that this bug is no longer reproducible, although this remains to be tested.
