### ISSUE TITLE
Weird bug on caption buttons with custom themes

### ISSUE THREAD

**Issue by twisty-nado** [QNetITQ/WaveFox#225]
theres these white buttons on the title bar buttons, im using ESR 115.9.1
![image](https://github.com/user-attachments/assets/a0bd699f-1f89-41f1-81e8-b33b20a17c47)

**Comment by QNetITQ** [comment]
Unofficial Windows themes are recognized by the browser as high-contrast with all the consequences that entails. These buttons cannot be fixed, but they can be hidden, but then it will be difficult for you to control the window through them.

**Comment by twisty-nado** [comment]
thats weird, because other themes like Echelon can make it work fine

**Comment by QNetITQ** [comment]
Yes, I once heard about the method with the manifest. If I'm not mistaken, this trick makes the browser think that it is running in the Windows 7 environment, because everything related to the DWM works as on Windows 7. In this case, the style for transparency to function is not needed. However, this also disables various optimizations designed for modern systems. Performance degradation is possible, and this method will not work with modern versions of the browser, since the Windows 7 code is physically absent.
