### ISSUE TITLE
Style.Compact-Plus gone?

### ISSUE THREAD

**Issue by K4sum1** [QNetITQ/WaveFox#57]
I upgraded my copy of WaveFox since 102 broke my old version a bit, but I noticed it wasn't as compact as the old version, then I noticed that the compact config is missing from the readme.

**Comment by QNetITQ** [comment]
Hello. Since version 100, Mozilla has increased the minimum tab bar height to 32px on Windows 10/11. You can install less, but the panel itself will not decrease. The compact plus mode is no longer possible under the new conditions. If I remember correctly, there is no such restriction on other systems, although I have not checked.

**Comment by QNetITQ** [comment]
You can try setting your own value, but I don't know how long it will work.
![изображение](https://user-images.githubusercontent.com/85301851/175183482-48ae81c9-4e6d-477f-bdbb-3e6d5e1283e4.png)

**Comment by K4sum1** [comment]
That appears to have worked for me, thanks.
