### ISSUE TITLE
Hamburger and other menus are ugly in compact mode

### ISSUE THREAD

**Issue by random-integer** [QNetITQ/WaveFox#6]
Hi! I love this theme very much. I have always missed the trapezoidal tabs from the old days. This brings it back really nicely! Thanks!

However, I noticed that when I select compact as my density, the hamburger menu in the top right corner becomes *super* compact.

Normal:

![normal](https://i.imgur.com/vKkvSri.png)

Compact:

![compact](https://i.imgur.com/WDClWkv.png)

I'm 80% sure that the menus in Compact weren't supposed to be *that* compact. Maybe you could fix this? Or maybe not because Compact is "not supported" anymore?

Steps to reproduce:  
1. Head to about:config and set the value of `browser.compactmode.show` to true
2. Right-click anywhere on the blank space of the tab bar.
3. Click "Customize Toolbar..."
4. In the bottom left corner, click "Density" and select "Compact (not supported)"
5. Close the "Customize Firefox" or "Customize Nightly" tab
6. Click the hamburger menu, the bookmarks menu, or the downloads menu.
7. Admire its compactness

Firefox Nightly, version 92.0a1, build ID 20210809093320 on Manjaro

**Comment by QNetITQ** [comment]
Hi. As planned, the compact mode will be used on monitors below 1080p, which is why the menus are made as compact as possible. I had plans for their revision, but all hands do not reach. Today I was going to upload an update with improvements, and since you have touched on this topic, I will try to add the ability to control the size of context menu items to the update. But if I do not have time to do it today, then I will add this feature in the next release.

**Comment by QNetITQ** [comment]
The sizes of elements can now be controlled in the section "User preferences". I have already set 4px, but you can set your own. Not all elements are well-crafted, but I will refine it in the future. Check the update

**Comment by random-integer** [comment]
Hi! I tried out the update and set `--menu-margin-padding` to 6px. It's compact and beautiful. Thanks! My favorite Firefox CSS theme so far!

![compact mode, menu margin padding 6px](https://i.imgur.com/oRSkVfe.png)
